[package]
org = "ballerinax"
name = "activemq.driver"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["ActiveMQ"]
repository = "https://github.com/ballerina-platform/module-ballerinax-activemq.driver"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "org.apache.activemq"
artifactId = "activemq-client"
version = "5.18.3"
path = "./lib/activemq-client-5.18.3.jar"

[[platform.java17.dependency]]
groupId = "org.apache.geronimo.specs"
artifactId = "geronimo-j2ee-management_1.1_spec"
version = "1.0.1"
path = "./lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar"

[[platform.java17.dependency]]
groupId = "org.fusesource.hawtbuf"
artifactId = "hawtbuf"
version = "1.11"
path = "./lib/hawtbuf-1.11.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "activemq.driver-native"
version = "1.0.0"
path = "../native/build/libs/activemq.driver-native-1.0.0-SNAPSHOT.jar"
